# Generated by Django 5.1.4 on 2025-01-09 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('type', models.CharField(choices=[('increase', 'Reward'), ('decrease', 'Penalty'), ('exchange', 'Exchange gift'), ('transfer', 'Transfer'), ('deposit', 'Deposit coin'), ('withdraw', 'Withdraw coin')], max_length=10, verbose_name='Event type')),
                ('coin', models.IntegerField(blank=True, null=True, verbose_name='coin')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Gift name')),
                ('coin', models.IntegerField(verbose_name='coin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('purchase_link', models.URLField(blank=True, null=True, verbose_name='Purchase link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Image file')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image link')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('increase', 'Reward'), ('decrease', 'Penalty'), ('exchange', 'Exchange gift'), ('transfer', 'Transfer'), ('deposit', 'Deposit coin'), ('withdraw', 'Withdraw coin')], max_length=10, verbose_name='Event type')),
                ('coin', models.IntegerField(verbose_name='coin')),
                ('from_wallet_before', models.IntegerField(blank=True, null=True, verbose_name='coin balance before transaction of sender')),
                ('from_wallet_after', models.IntegerField(blank=True, null=True, verbose_name='coin balance after transaction of sender')),
                ('to_wallet_before', models.IntegerField(blank=True, null=True, verbose_name='coin balance before transaction of receiver')),
                ('to_wallet_after', models.IntegerField(blank=True, null=True, verbose_name='coin balance after transaction of receiver')),
                ('fee', models.IntegerField(default=0, verbose_name='Transaction fee')),
                ('admin_wallet_before', models.IntegerField(blank=True, null=True, verbose_name='coin balance before transaction of admin')),
                ('admin_wallet_after', models.IntegerField(blank=True, null=True, verbose_name='coin balance after transaction of admin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.event', verbose_name='Event')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.gift', verbose_name='Gift')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'permissions': [('change_transaction_status', 'Can change transaction status')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.IntegerField(default=0, verbose_name='coin balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'permissions': [('change_wallet_balance', 'Can change wallet balance')],
            },
        ),
    ]
