# Generated by Django 5.1.4 on 2025-02-19 10:32

import contract.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('salary_gross', models.IntegerField(default=0, verbose_name='Gross Salary')),
                ('salary_basic', models.IntegerField(default=0, verbose_name='Basic Salary')),
                ('allowance_clothing', models.IntegerField(default=415000, verbose_name='Clothing Allowance')),
                ('allowance_lunch', models.IntegerField(default=730000, verbose_name='Lunch Allowance')),
                ('allowance_housing', models.IntegerField(default=0, verbose_name='Housing Allowance')),
                ('allowance_phone', models.IntegerField(default=0, verbose_name='Phone Allowance')),
                ('allowance_fuel', models.IntegerField(default=0, verbose_name='Fuel Allowance')),
                ('allowance_position', models.IntegerField(default=0, verbose_name='Position Allowance')),
                ('allowance_responsibility', models.IntegerField(default=0, verbose_name='Responsibility Allowance')),
                ('bonus_kpi', models.IntegerField(default=0, verbose_name='KPI Bonus')),
                ('deduction_personal', models.IntegerField(default=11000000, verbose_name='Personal Deduction')),
                ('number_dependents', models.IntegerField(default=0, verbose_name='Number of Dependents')),
                ('signing_date', models.DateField(verbose_name='Contract Signing Date')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Contract Start Date')),
                ('end_date', models.DateField(default=contract.models.default_end_date, verbose_name='Contract End Date')),
                ('is_current_contract', models.BooleanField(default=True, verbose_name='Current Contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contract',
            },
        ),
    ]
