# Generated by Django 5.1.4 on 2025-02-17 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('take_leave_month', models.FloatField(verbose_name='Take leave this month')),
                ('leave_taken', models.FloatField(verbose_name='Number of days off during the year')),
                ('maximum_leave', models.IntegerField(verbose_name='Maximum leave')),
                ('working_days_month', models.FloatField(verbose_name='Number of working days in the month')),
                ('actual_ot', models.FloatField(verbose_name='Actual OT hours')),
                ('coefficient_ot', models.FloatField(verbose_name='Number of OT hours multiplied by coefficient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_migration_attendance_user_date')],
            },
        ),
    ]
