# Generated by Django 5.1.4 on 2025-03-06 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_income', models.IntegerField(default=0, verbose_name='Total income')),
                ('daily_wage', models.IntegerField(default=0, verbose_name='100% Daily Wage')),
                ('overtime_taxable', models.IntegerField(default=0, verbose_name='Overtime (Taxable)')),
                ('overtime_non_taxable', models.IntegerField(default=0, verbose_name='Overtime (Non-Taxable)')),
                ('employee_insurance_social', models.IntegerField(default=0, verbose_name='Employee Social Insurance')),
                ('employee_insurance_health', models.IntegerField(default=0, verbose_name='Employee Health Insurance')),
                ('employee_insurance_unemployment', models.IntegerField(default=0, verbose_name='Employee Unemployment Insurance')),
                ('count_employee_insurance', models.IntegerField(default=0, verbose_name='Employee Insurance')),
                ('enterprise_insurance_social', models.IntegerField(default=0, verbose_name='Enterprise Social Insurance')),
                ('enterprise_insurance_health', models.IntegerField(default=0, verbose_name='Enterprise Health Insurance')),
                ('enterprise_insurance_unemployment', models.IntegerField(default=0, verbose_name='Enterprise Unemployment Insurance')),
                ('count_enterprise_insurance', models.IntegerField(default=0, verbose_name='Enterprise Insurance')),
                ('personal_income_tax', models.IntegerField(default=0, verbose_name='Personal Income Tax ')),
                ('taxable_income', models.IntegerField(default=0, verbose_name='Taxable Income')),
                ('dependent', models.IntegerField(default=0, verbose_name='Dependent')),
                ('taxable_earnings', models.IntegerField(default=0, verbose_name='Taxable Earnings')),
                ('tax_underpaid_or_overpaid', models.IntegerField(default=0, verbose_name='Personal Income Tax Underpaid/Overpaid (if any)')),
                ('income_additional', models.IntegerField(default=0, verbose_name='Additional Income')),
                ('income_deduction', models.IntegerField(default=0, verbose_name='Income Deduction')),
                ('other', models.IntegerField(default=0, verbose_name='Other')),
                ('working_day', models.FloatField(default=0, verbose_name='Working day')),
                ('count_other_income', models.IntegerField(default=0, verbose_name='Other Income / Deductions')),
                ('actual_income', models.IntegerField(default=0, verbose_name='Actual Income')),
                ('file_payslip', models.CharField(blank=True, max_length=255, null=True)),
                ('file_payslip_protect', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salary',
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_migration_salary_user_date')],
            },
        ),
    ]
